jira_instance_url = "https://jira.pbs.one/"
jira_key_file = "key.txt"
queries_definition_file = "queries.yaml"
result_files_dir = "./results"
alert_sound_file = "finealert.wav"
all_issues_file = "all_issues.txt"
